server:
  port: 0

spring:
  application:
    name: capstone-cell-service
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true # 외부 접속 허용
      path: /h2-console
  datasource:
    url: jdbc:mariadb://49.50.163.44:3306/capstone?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

cloud:
  aws:
    s3:
      bucket: capstone-taekang-bucket
    credentials:
      access-key: 1
      secret-key: 1
    region:
      static: ap-northeast-2
    stack:
      auto: false

logging:
  level:
    com.example.capstonecellservice: DEBUG
